CREATE DATABASE IF NOT EXISTS esp8266_db;

USE esp8266_db;

CREATE TABLE IF NOT EXISTS led_status (
    id INT AUTO_INCREMENT PRIMARY KEY,
    status VARCHAR(10) NOT NULL,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);
